# This file was generated by GoReleaser. DO NOT EDIT.
cask "3gpp-mcp" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "17a34d27648293290948a1afc3278268d208e87da3a164f6f33ef65a095d783b"
      url "https://github.com/higebu/3gpp-mcp/releases/download/v#{version}/3gpp-mcp_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "14ee98a0b5c0d73985c338a55d6c680280a2b7c4868e598134a945fc7a436e4f"
      url "https://github.com/higebu/3gpp-mcp/releases/download/v#{version}/3gpp-mcp_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4d5504f2b546b4cb82fa16bcfc284e6ae01602552695579665b524517f87a00c"
      url "https://github.com/higebu/3gpp-mcp/releases/download/v#{version}/3gpp-mcp_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "457ed53937931d8c822e44e61c9e5a8905a6fe602f6dbd35391ee2c6a29ce3ba"
      url "https://github.com/higebu/3gpp-mcp/releases/download/v#{version}/3gpp-mcp_Linux_arm64.tar.gz"
    end
  end

  name "3gpp-mcp"
  desc "MCP server for 3GPP specification documents"
  homepage "https://github.com/higebu/3gpp-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "3gpp-mcp"

  generate_completions_from_executable "3gpp-mcp", "completion",
    shell_parameter_format: "argument",
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
