# This file was generated by GoReleaser. DO NOT EDIT.
cask "3gpp-mcp" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "19c4e032327681542bae93122af99932ec7ec979314e06886f082b3b15447e3a"
      url "https://github.com/higebu/3gpp-mcp/releases/download/v#{version}/3gpp-mcp_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d8e745e9589901d30911181b9ee35c81d26b87f7850ad7a24c6ef53bec3c6474"
      url "https://github.com/higebu/3gpp-mcp/releases/download/v#{version}/3gpp-mcp_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cbc76c89ac5b01760d6d07df2c989a0a64ed758fa9d6de69183d94a037cb866d"
      url "https://github.com/higebu/3gpp-mcp/releases/download/v#{version}/3gpp-mcp_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "62922a24f44fea3339915e9f5b74cdb7e475041b56bff8aa1b13cb4227ca4af4"
      url "https://github.com/higebu/3gpp-mcp/releases/download/v#{version}/3gpp-mcp_Linux_arm64.tar.gz"
    end
  end

  name "3gpp-mcp"
  desc "MCP server for 3GPP specification documents"
  homepage "https://github.com/higebu/3gpp-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "3gpp-mcp"

  generate_completions_from_executable "3gpp-mcp", "completion",
    shell_parameter_format: "argument",
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
