# This file was generated by GoReleaser. DO NOT EDIT.
cask "3gpp-mcp" do
  version "0.1.6"

  on_macos do
    on_intel do
      sha256 "383efe1d58026c0322d50342e967f9ae6076319273c31c3b1c1df0a85c4d1a05"
      url "https://github.com/higebu/3gpp-mcp/releases/download/v#{version}/3gpp-mcp_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "379b860716f99d92f39b898d9f8f197188cf1fbdb92054da3683d3867c55caa7"
      url "https://github.com/higebu/3gpp-mcp/releases/download/v#{version}/3gpp-mcp_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ccdd1b4e240c829c1688a35a406560c4328aabefdcd9805ec8430d9672459a61"
      url "https://github.com/higebu/3gpp-mcp/releases/download/v#{version}/3gpp-mcp_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2bdd648e6bcafb6fae1bbed5b92f197b564fe23c6e23a55be3aaee8e5728d2e9"
      url "https://github.com/higebu/3gpp-mcp/releases/download/v#{version}/3gpp-mcp_Linux_arm64.tar.gz"
    end
  end

  name "3gpp-mcp"
  desc "MCP server for 3GPP specification documents"
  homepage "https://github.com/higebu/3gpp-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "3gpp-mcp"

  generate_completions_from_executable "3gpp-mcp", "completion",
    shell_parameter_format: "argument",
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
