# This file was generated by GoReleaser. DO NOT EDIT.
cask "rfc-mcp" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "ff394a5b6172667da28e25119fc309b1859e24f0d06433b76a27b7aaf782df54"
      url "https://github.com/higebu/rfc-mcp/releases/download/v#{version}/rfc-mcp_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c3cf2d3771c707e743ed20236c19b718cd46dcfd4e57f4496cf02797f3344458"
      url "https://github.com/higebu/rfc-mcp/releases/download/v#{version}/rfc-mcp_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ec5b8aa3218b904d7e4eab7e992a3d2c5e2adf73242ca08a0be354b7c77d0de0"
      url "https://github.com/higebu/rfc-mcp/releases/download/v#{version}/rfc-mcp_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ed5cda90a5f3128290f5b1a535d7880f5c6585f2df36c7856d0a60fa208adede"
      url "https://github.com/higebu/rfc-mcp/releases/download/v#{version}/rfc-mcp_Linux_arm64.tar.gz"
    end
  end

  name "rfc-mcp"
  desc "MCP server for IETF RFC documents"
  homepage "https://github.com/higebu/rfc-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rfc-mcp"

  generate_completions_from_executable "rfc-mcp", "completion",
    shell_parameter_format: "argument",
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
